# Generated by Django 6.0.6 on 2026-06-12 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto del crédito')),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='plazo (meses)')),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tasa de interés anual (%)')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('active', 'Activo'), ('rejected', 'Rechazado'), ('paid_off', 'Pagado')], default='pending', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='clients.client')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='número de cuota')),
                ('due_date', models.DateField(verbose_name='fecha de vencimiento')),
                ('capital_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto de capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto de interés')),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor de la cuota')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='saldo pendiente después de esta cuota')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida')], default='pending', max_length=10, verbose_name='estado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credits.credit')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['credit', 'installment_number'],
                'unique_together': {('credit', 'installment_number')},
            },
        ),
    ]
