# Generated by Django 6.0.6 on 2026-06-12 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='fecha de pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto pagado')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='número de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('amortization_schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='credits.amortizationschedule', verbose_name='cuota')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
