# Generated by Django 6.0.6 on 2026-06-12 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('document_type', models.CharField(default='CC', max_length=20, verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')], verbose_name='número de documento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ingresos mensuales')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
